POST https://192.168.2.70:8088/mposcbc/callback
content-type: application/json

{
"param1": "wallet_cbc@payable.lk",
"param2": "@Abc321#",
"txnrespcode": "EN00",
"txndescription": "Success",
"txnrrn": "118453557999",
"txnstan": "126606499",
"txnamount": "10.50",
"tipvalue": "0",
"txndatetime": "2020-06-16 3:55:17",
"custcardnumber": "421689******5767",
"interchange": "C",
"approvalcode": "002607",
"mid": "20147000000508",
"tid": "20000737"
}